### ISSUE TITLE
github-comments-editor doesn't work with pull requests

### ISSUE THREAD

**Issue by aspiers** [Hansimov/Small-Scripts-and-Tiny-Tools#3]
Currently the header has

    // @match        https://github.com/*/issues/*

which doesn't match pull requests, but it's extremely common to need to write comments in pull requests as well as issues.

**Comment by aspiers** [comment]
Ah, I see you have this in a TODO list in [the README](https://github.com/Hansimov/Small-Scripts-and-Tiny-Tools/tree/master/github-comments-editor) :-)  Given that the userscript is for making it easier to work with GitHub issues, I think it would make sense if you converted your TODO list into a series of GitHub issues :-)  That would not only allow dog-fooding but also make it possible to manage the various issues via labels / milestones / projects, which might encourage other people to help out.

**Comment by Hansimov** [comment]
@aspiers 

Ah, sorry for replying to your comments so late!
I have been working on a lot of other issues these days and have not noticed this repo for a long time.
Thanks for your fork and nice comments.

Yes, there are too many TODOs ...
At the beginning, I write this script just for personal use. So I just put it into the `Small-Scripts-and-Tiny-Tools`.
I think it may be better to seperate this script to a new repo so that other small scripts won't pollute this one.

I will do the movement after a few days, and then we can work together to make this script better!

**Comment by aspiers** [comment]
That sounds like a great idea - thank you so much!

**Comment by aspiers** [comment]
Moved to https://github.com/Hansimov/github-writing-editor/issues/3
