### ISSUE TITLE
github-comments-editor doesn't clear preview after comment is submitted

### ISSUE THREAD

**Issue by aspiers** [Hansimov/Small-Scripts-and-Tiny-Tools#6]
When I submit a comment, the text in the preview box still remains.

**Comment by aspiers** [comment]
For example, after typing this and clicking the `Comment` button, I will still see this sentence in the box to the right of where I'm typing.

**Comment by Hansimov** [comment]
@aspiers 
Yes, this issue has already been considered in the `README.md`:

```
* Improve markdown preview engine:
  * ...
  * ...
  * Clear preview content after the new comment is submitted
```

I have transfered this repo to this new one: [github-writing-editor](https://github.com/Hansimov/github-writing-editor).
You can fork the new repo, and we can work togerther to make this userscript better.

BTW, the `Small-Scripts-and-Tiny-Tools` repo will be deleted after you read this comment.
Because I find that it is better to seperate the scripts to different repos and then there is no need for this one to exist.

**Comment by aspiers** [comment]
Great thanks. Yes it makes sense to separate the scripts into different repos.  Please don't delete the repo though!  Reasons:

1. There are all the issues I submitted which need transferring
2. There are links from elsewhere (e.g. mottie's repo) to this one.

So please make the repo an empty redirect instead.

**Comment by Hansimov** [comment]
@aspiers
Thanks for your good advice.

I have changed the link in the pull request of mottie's repo immediately to the new one after it is created.
For your issues and pull requests, while you finish your transferring, please inform me of that. Without your confirmation, I will not delete this repo.

It will reduce conflicts if there is only one `github-writing-editor` repo existing. Redirecting is also a good choice, but only one repo will avoid lots of troubles if other people would like to contribute to this repo someday.

Look forwards to seeing more issues and pull requests from you!

**Comment by aspiers** [comment]
Moved to https://github.com/Hansimov/github-writing-editor/issues/1
